# Generated by Django 5.0.3 on 2024-04-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_topic_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='creater',
            field=models.CharField(default='mini', max_length=11),
        ),
    ]
