# Generated by Django 5.0.3 on 2024-04-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_webpage_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecords',
            name='type',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
