# Generated by Django 5.0.3 on 2024-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_accessrecords_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('empno', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('mgr', models.IntegerField()),
                ('hiredate', models.DateField(auto_now=True)),
                ('sal', models.IntegerField()),
                ('comm', models.IntegerField()),
                ('deptno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
