# Generated by Django 5.0.3 on 2024-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptno', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
                ('dloc', models.CharField(default='marathali', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='emp',
        ),
    ]
