# Generated by Django 5.0.3 on 2024-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_salgrade_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='empno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emp',
            name='ename',
            field=models.CharField(max_length=100),
        ),
    ]
